// Custom production server that adds WebSocket proxy support.
// The Next.js standalone server.js handles HTTP rewrites but does NOT proxy
// WebSocket upgrade requests.  This wrapper intercepts /ws/* upgrades and
// forwards them to the backend.

const { createServer } = require('http');
const { request: httpRequest } = require('http');
const { parse } = require('url');

// Load the Next.js standalone handler (auto-generated by `next build`)
const NextServer = require('next/dist/server/next-server').default;

const hostname = process.env.HOSTNAME || '0.0.0.0';
const port = parseInt(process.env.PORT || '3000', 10);
const backendUrl = process.env.BACKEND_INTERNAL_URL || 'http://backend:8000';

const conf = require('./.next/required-server-files.json').config;

const nextServer = new NextServer({
  hostname,
  port,
  dir: __dirname,
  dev: false,
  customServer: true,
  conf,
});

const handler = nextServer.getRequestHandler();

const server = createServer((req, res) => {
  handler(req, res, parse(req.url || '', true));
});

// ── WebSocket proxy ──────────────────────────────────────────────────────────

server.on('upgrade', (req, socket, head) => {
  const { pathname } = parse(req.url || '');

  if (pathname && pathname.startsWith('/ws/')) {
    const target = new URL(backendUrl);

    const proxyReq = httpRequest({
      hostname: target.hostname,
      port: target.port || 8000,
      path: req.url,
      method: req.method,
      headers: {
        ...req.headers,
        host: target.host,
      },
    });

    proxyReq.on('upgrade', (proxyRes, proxySocket, proxyHead) => {
      // Forward the raw HTTP 101 Switching Protocols response
      const responseHeaders = Object.entries(proxyRes.headers)
        .map(([key, val]) => `${key}: ${val}`)
        .join('\r\n');
      socket.write(
        `HTTP/1.1 101 Switching Protocols\r\n${responseHeaders}\r\n\r\n`,
      );
      if (proxyHead && proxyHead.length) {
        socket.write(proxyHead);
      }

      // Bi-directional pipe
      proxySocket.pipe(socket);
      socket.pipe(proxySocket);

      proxySocket.on('error', () => socket.destroy());
      socket.on('error', () => proxySocket.destroy());
    });

    proxyReq.on('response', (res) => {
      // Backend rejected the upgrade (e.g. 401) — relay the status to the client
      const responseHeaders = Object.entries(res.headers)
        .map(([key, val]) => `${key}: ${val}`)
        .join('\r\n');
      socket.write(
        `HTTP/1.1 ${res.statusCode} ${res.statusMessage}\r\n${responseHeaders}\r\n\r\n`,
      );
      res.pipe(socket);
    });

    proxyReq.on('error', () => {
      socket.destroy();
    });

    if (head && head.length) {
      proxyReq.write(head);
    }
    proxyReq.end();
  }
  // Non /ws/ upgrades are ignored (Next.js doesn't need them in production)
});

// ── Start ────────────────────────────────────────────────────────────────────

server.listen(port, hostname, () => {
  console.log(`> Ready on http://${hostname}:${port}`);
});
